final Map<String, String> weatherWords = {
  'clear sky': 'thoáng đãng',
  'few clouds': 'ít mây',
  'scattered clouds': 'mây rải rác',
  'broken clouds': 'mây đen',
  'shower rain': 'mưa rào',
  'rain': 'mưa',
  'light rain': 'mưa nhẹ hạt',
  'drizzle': 'mưa phùn',
  'thunderstorm with light rain': 'giông, mưa nhẹ hạt',
  'thunderstorm with rain': 'giông và mưa',
  'thunderstorm with heavy rain': 'giông và mưa lớn',
  'light thunderstorm': 'giông nhẹ',
  'thunderstorm': 'giông bão',
  'heavy thunderstorm': 'giông bão lớn',
  'thunderstorm with light drizzle': 'giông, kèm mưa phùn',
  'thunderstorm with drizzle': 'giông, mưa phùn',
  'thunderstorm with light drizzle': 'giông, kèm mưa phùn',
  'thunderstorm with drizzle': 'giông kèm mưa phùn',
  'thunderstorm': 'sấm chớp',
  'snow': 'tuyết',
  'mist': 'sương',
  'moderate rain': 'mưa vừa',
  'heavy intensity rain': 'mưa to',
  'very heavy rain': 'mưa nặng hạt',
  'extreme rain': 'mưa rất to',
  'freezing rain': 'mưa rét',
  'light intensity shower rain': 'mưa rào',
  'heavy intensity shower rain': 'mưa nặng hạt',
  'ragged shower rain': 'mưa rải rác',
  'smoke': 'khói',
  'haze': 'sương mù',
  'dust': 'bụi',
  'fog': 'sương',
  'fog': 'sương',
  'dust whirls': 'bụi xoáy',
  'sand/ dust whirls': 'bụi xoáy',
  'sand / dust whirls': 'bụi xoáy',
  'sand /dust whirls': 'bụi xoáy',
  'squalls': 'mưa đá',
  'tornado': 'lốc xoáy'
};

final Map<String, String> iconWords = {
  '01d': 'thoáng đãng',
  '01n': 'thoáng đãng',
  '02d': 'ít mây',
  '02n': 'ít mây',
  '03d': 'mây rải rác',
  '03n': 'mây rải rác',
  '04d': 'mây đen',
  '04n': 'mây đen',
  '09d': 'mưa nhỏ',
  '09n': 'mưa nhỏ',
  '10d': 'mưa',
  '10n': 'mưa',
  '11d': 'sấm chớp',
  '11n': 'sấm chớp',
  '13d': 'tuyết',
  '13n': 'tuyết',
  '50d': 'sương mù',
  '50n': 'sương mù',
};

class WeatherVietsub {
  static String iconCode(String code) => iconWords[code.toLowerCase()];
  static String word(String word) => weatherWords[word.toLowerCase()];
}
